#!/bin/sh

RET=1

printf "Checking $i for CHANGELOG changes"
if git log --name-only --oneline --pretty="format:" HEAD..."$1" | grep -qsE "CHANGELOG.md"
then
    RET=0
else
    printf "missing changelog update"
fi

exit $RET