#!/bin/sh

RET=1

printf "Checking for CHANGELOG changes"
if git log --name-only --oneline --pretty="format:" "$1" | grep -q "CHANGELOG.md"
then
    RET=0
else
    printf "missing changelog update"
fi

exit $RET
