#!/bin/sh

RET=1

git log --name-only "$1"..."$2"

if git log --name-only --oneline --pretty="format:" "$1"..."$2" | grep -qs "$3"
then
    RET=0
else
    printf "missing changelog update"
fi

exit $RET
