#!/bin/sh

RET=1

git log --name-only "origin/$1"..."origin/$2"

if git log --name-only --oneline --pretty="format:" "origin/$1"..."origin/$2" | grep -qs "$3"
then
    RET=0
else
    printf "missing changelog update"
fi

exit $RET
