name: Pull Request Checks
on: pull_request

jobs:
  changelog-updated:
    name: CHANGELOG updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./github/scripts/file-changed-check "${GITHUB_SHA}" "CHANGELOG\.md"
  unit-tests-updated:
    name: Unit tests updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./github/scripts/file-changed-check "${GITHUB_SHA}" "test/[a-z]+\.jl"
  docs-updated:
    name: Documentation updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./github/scripts/file-changed-check "${GITHUB_SHA}" "docs/[a-z]+\.jl"