name: Pull Request Checks
on: pull_request

jobs:
  changelog-updated:
    name: CHANGELOG updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: .github/scripts/file-changed-check "${{ github.head_ref }}" "${{ github.base_ref }}" "CHANGELOG\.md"
  unit-tests-updated:
    name: Unit tests updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: .github/scripts/file-changed-check "${{ github.head_ref }}" "${{ github.base_ref }}" "test/[a-z]+\.jl"
  docs-updated:
    name: Documentation updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: .github/scripts/file-changed-check "${{ github.head_ref }}" "${{ github.base_ref }}" "docs/[a-z]+\.jl"